import xml.etree.ElementTree as ET
from QualysCommon import QualysAPI


def responseHandler(resp: ET.Element):
    if resp is None:
        return False
    if type(resp) is not ET.Element:
        print('API Error: Unable to determine response')
        return False
    if resp.find('.//CODE') is not None:
        print('ERROR: %s\n%s' % (resp.find('.//CODE').text, resp.find('.//TEXT').text))
        return False
    return True


def getVirtualHosts(source_api: QualysAPI.QualysAPI, networks: bool = False):
    """
    Get the virtual hosts from a subscription

    Parameters:
        source_api:             An object of the class QualysAPI
        networks:               (Optional) A boolean value.  If True, includes Network ID for each Virtual Host
                                Defaults to False

    Returns:
        hostlist:               A list of python dictionaries, each containing the keys 'IP', 'PORT', 'FQDNS' and
                                optionally 'NETWORK_ID', and their corresponding values
    """
    hostlist = []

    fullurl = '%s/api/2.0/fo/asset/vhost/?action=list' % source_api.server
    resp = source_api.makeCall(url=fullurl, method='GET')
    if not responseHandler(resp):
        print('QualysVirtualHostProcessor.getVirtualHosts ERROR: Could not obtain  Virtual Host list from source')
        return None
    if resp.find('RESPONSE/VIRTUAL_HOST_LIST') is not None:
        for host in resp.findall('.//VIRTUAL_HOST'):
            vhost = {}
            fqdns = []
            vhost['IP'] = host.find('IP').text
            vhost['PORT'] = host.find('PORT').text
            for fqdn in host.findall('FQDN'):
                fqdns.append(fqdn.text)
            vhost['FQDNS'] = fqdns
            if networks:
                if host.find('NETWORK_ID') is None:
                    print('QualysVirtualHostProcessor.getVirtualHosts ERROR: Networks enabled but no Network ID found')
                    return None
                vhost['NETWORK_ID'] = host.find('NETWORK_ID').text
            hostlist.append(vhost)
    else:
        print('QualysVirtualHostProcessor.getVirtualHosts ERROR: Cannot find Virtual Host List in output')
        return None

    return hostlist


def convertVirtualHost(vhost: dict):
    """
    Converts a Virtual Hosts generated by getVirtualHosts() into a URL, excluding the FQDN, used in an API call
    to recreate it

    Parameters:
        vhost:              A python dictionary containing the keys 'IP', 'PORT', 'FQDNS' and optionally 'NETWORK_ID'
                            with their corresponding values

    Returns:
        url:                The URL, excluding the FQDN, of the API call used to create the Virtual Host
    """
    url = '/api/2.0/fo/asset/vhost/?action=create&ip=%s&port=%s&fqdn=%s' % (
            vhost['IP'],
            vhost['PORT'],
            ','.join(vhost['FQDNS'])
        )
    if 'NETWORK_ID' in vhost.keys():
        url = '%s&network_id=%s' % (url, vhost['NETWORK_ID'])
    return url


def convertVirtualHosts(vhostlist: list):
    """
    Converts a list Virtual Hosts generated by getVirtualHosts() into URLs, excluding the FQDN, used in API calls
    to recreate them

    Parameters:
        vhost:              A python dictionary containing the keys 'IP', 'PORT', 'FQDNS' and optionally 'NETWORK_ID'
                            with their corresponding values

    Returns:
        urllist:                The list of URLs, excluding the FQDN, of the API calls used to create the Virtual Hosts
    """
    urllist = []
    vhost: dict
    for vhost in vhostlist:
        url = '/api/2.0/fo/asset/vhost/?action=create&ip=%s&port=%s&fqdn=%s' % (
            vhost['IP'],
            vhost['PORT'],
            ','.join(vhost['FQDNS'])
        )
        if 'NETWORK_ID' in vhost.keys():
            url = '%s&network_id=%s' % (url, vhost['NETWORK_ID'])
        urllist.append(url)
    return urllist


def createVirtualHosts(urllist: list, target_api: QualysAPI.QualysAPI):
    """
    Creates Virtual Hosts from a list of virtual host URLs generated by convertVirtualHosts()

    Parameters:
        urllist:            A list of strings containing URLs, excluding the FQDN, to use in API calls to create
                            Virtual Hosts
        target_api:         An object of the class QualysAPI

    Returns:
        True                if all Virtual Hosts were successfully created
        False               on the first occurrence of an error in the API response
    """
    for url in urllist:
        fullurl = '%s%s' % (target_api.server, url)
        resp = target_api.makeCall(url=fullurl)
        if not responseHandler(resp):
            print('QualysVirtualHostProcessor.createVirtualHosts ERROR: Could not validate response')
            return False
    return True


def createVirtualHost(target_api: QualysAPI.QualysAPI, url: str):
    """
    Creates a Virtual Hosts from a virtual host URL generated by convertVirtualHost()

    Parameters:
        url:                A string value containing the URL, excluding the FQDN, to use in an API call to create
                            a single Virtual Host
        target_api:         An object of the class QualysAPI

    Returns:
        True                if the Virtual Hosts was successfully created
        False               if there was an error in the API response
    """

    fullurl = '%s%s' % (target_api.server, url)
    resp = target_api.makeCall(url=fullurl)
    if not responseHandler(resp):
        return None
    return resp
